version: '3'
services:
  mangodb_standalone:
    image: mongo:5.0
    ports:
      - 27017:27017
    command: mongod --dbpath /data/db --port 27017 --config /resource/mongod.yml
    volumes:
      - ./standalone/config/mongod.yml:/resource/mongod.yml
      - ./standalone/data:/data/db
    networks:
      redis-cluster-net:
          ipv4_address: 192.168.200.222
networks:
    redis-cluster-net:
        external:
            name: redis-cluster-net
