version: '3.3'

networks:
    redis-cluster-net:
        external:
            name: redis-cluster-net

services:
  database:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'   
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '1234'      
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
      - './conf/my.cnf:/etc/my.cnf'
    command:
      #id唯一
      --server_id=100
      --log-bin=mysql-bin
      --sync_binlog=1
      --binlog-ignore-db=mysql
      --binlog_format=row
      --expire_logs_days=7
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    networks:
      redis-cluster-net:
          ipv4_address: 192.168.200.201
